/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameMaestroDetalle.java
 *
 * Created on 01/07/2009, 09:28:50 AM
 */
package gestiontipocampo;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;

/// <summary>
/// Clase que contiene la interfaz de las relaciones simétricas
/// </summary>
public class frameSimetria extends javax.swing.JFrame {

    /** Creates new form frameMaestroDetalle */
    Vector modeloForm1Seleccionados;
    Vector modeloForm1CamposDisponibles;
    Vector modeloForm2Seleccionados;
    Vector modeloForm2CamposDisponibles;
    Simetria simetria;
    public Formulario formulario;

    /// <summary>
    /// Constructor por defecto
    /// </summary>
    public frameSimetria() {
        initComponents();
        formulario = new Formulario();
        llenarComboFormularios();
        simetria = new Simetria();
        modeloForm1Seleccionados = new Vector();
        modeloForm2Seleccionados = new Vector();

    }

    private void llenarComboFormularios() {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) comboForm1.getModel();
        modelo.removeAllElements();
        modelo2.removeAllElements();
        formulario = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getTodosLosFormulario();
        int id;
        String nombreForm;
        for (int i = 0; i < forms.size(); i++) {
            id = Integer.parseInt(forms.get(i).toString());
            i++;
            nombreForm = forms.get(i).toString();
            modelo.addElement(new MiDato(nombreForm, id));
            modelo2.addElement(new MiDato(nombreForm, id));
        }
        comboForm1.setModel(modelo);
        comboForm2.setModel(modelo2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboForm1 = new javax.swing.JComboBox();
        comboForm2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCamposForm1Disponibles = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCampoForm2Disponibles = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCamposForm1Seleccionados = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCamposForm2Seleccionados = new javax.swing.JList();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCargarCamposForm1 = new javax.swing.JButton();
        btnCargarCamposForm2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboCampoLlaveForm1 = new javax.swing.JComboBox();
        comboCampoLlaveForm2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        comboForm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboForm1.setName("comboForm1"); // NOI18N
        comboForm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboForm1MouseReleased(evt);
            }
        });
        comboForm1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboForm1ItemStateChanged(evt);
            }
        });
        comboForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboForm1ActionPerformed(evt);
            }
        });

        comboForm2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboForm2.setName("comboForm2"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaCamposForm1Disponibles.setName("listaCamposForm1Disponibles"); // NOI18N
        listaCamposForm1Disponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCamposForm1DisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCamposForm1Disponibles);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listaCampoForm2Disponibles.setName("listaCampoForm2Disponibles"); // NOI18N
        listaCampoForm2Disponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCampoForm2DisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaCampoForm2Disponibles);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        listaCamposForm1Seleccionados.setName("listaCamposForm1Seleccionados"); // NOI18N
        jScrollPane3.setViewportView(listaCamposForm1Seleccionados);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        listaCamposForm2Seleccionados.setName("listaCamposForm2Seleccionados"); // NOI18N
        jScrollPane4.setViewportView(listaCamposForm2Seleccionados);

        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnCargarCamposForm1.setText(resourceMap.getString("buttonDesplegarTiposCampoMaestro.text")); // NOI18N
        btnCargarCamposForm1.setName("buttonDesplegarTiposCampoMaestro"); // NOI18N
        btnCargarCamposForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCamposForm1ActionPerformed(evt);
            }
        });

        btnCargarCamposForm2.setText(resourceMap.getString("btnCargarCamposForm2.text")); // NOI18N
        btnCargarCamposForm2.setName("btnCargarCamposForm2"); // NOI18N
        btnCargarCamposForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCamposForm2ActionPerformed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        comboCampoLlaveForm1.setName("comboCampoLlaveForm1"); // NOI18N
        comboCampoLlaveForm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboCampoLlaveForm1MouseReleased(evt);
            }
        });
        comboCampoLlaveForm1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCampoLlaveForm1ItemStateChanged(evt);
            }
        });
        comboCampoLlaveForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoLlaveForm1ActionPerformed(evt);
            }
        });

        comboCampoLlaveForm2.setName("comboCampoLlaveForm2"); // NOI18N
        comboCampoLlaveForm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboCampoLlaveForm2MouseReleased(evt);
            }
        });
        comboCampoLlaveForm2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCampoLlaveForm2ItemStateChanged(evt);
            }
        });
        comboCampoLlaveForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoLlaveForm2ActionPerformed(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboCampoLlaveForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarCamposForm1)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(comboCampoLlaveForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarCamposForm2))
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarCamposForm1))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(comboCampoLlaveForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboForm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarCamposForm2))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(comboCampoLlaveForm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboForm1ActionPerformed
        /*    System.out.print("ID" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloMaestroCamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);


        comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCamposMaestroDisponibles.setListData(modeloMaestroCamposDisponibles);
        
        /*
        System.out.print("asdfasdf" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getMiembrosFormularioPorID(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);
        int id;
        String tipoCampo;
        int tipoDeTipoCampo;
        for (int i = 0; i < forms.size(); i++) {
        id = Integer.parseInt(forms.get(i).toString());
        i++;
        tipoCampo = forms.get(i).toString();
        i++;
        tipoDeTipoCampo = Integer.parseInt(forms.get(i).toString());
        modelo.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
        modelo2.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
        }

        //comboCampoInicial.setModel(modelo);
        // comboCampoFinal.setModel(modelo2);

        comboFormularioDetalle.setModel(modelo);*/
}//GEN-LAST:event_comboForm1ActionPerformed

    private void comboForm1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboForm1ItemStateChanged
    }//GEN-LAST:event_comboForm1ItemStateChanged

    private void btnCargarCamposForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCamposForm1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.println("ID" + "  " + ((MiDato) comboForm1.getSelectedItem()).ID + " nombre" + "  " + ((MiDato) comboForm1.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();

        /***********Se llena la lista de los campos disponibles****************/
        modeloForm1CamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm1.getSelectedItem()).ID);
        listaCamposForm1Disponibles.setListData(modeloForm1CamposDisponibles);
        /***********Se llena el combo de campos llave****************/
        javax.swing.DefaultComboBoxModel modeloCamposForm1 = new javax.swing.DefaultComboBoxModel();

        Vector vectorCampos = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm1.getSelectedItem()).ID);

        for (int i = 0; i < vectorCampos.size(); i++) {
            modeloCamposForm1.addElement(vectorCampos.get(i)/*.toString()*/);
        }
        comboCampoLlaveForm1.setModel(modeloCamposForm1);
    }//GEN-LAST:event_btnCargarCamposForm1ActionPerformed

    private void comboForm1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboForm1MouseReleased
    }//GEN-LAST:event_comboForm1MouseReleased

    private void listaCamposForm1DisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCamposForm1DisponiblesMouseClicked
        // TODO add your handling code here:


        modeloForm1Seleccionados.add(listaCamposForm1Disponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposForm1Seleccionados.setListData(modeloForm1Seleccionados);
        int a = listaCamposForm1Disponibles.getSelectedIndex();
        System.out.print("aa: " + a);
        //modeloMaestroSeleccionados.remove(a);
        modeloForm1CamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCamposForm1Disponibles.setListData(modeloForm1CamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT

    }//GEN-LAST:event_listaCamposForm1DisponiblesMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
        //maestroDetalle.formularioMaestro=(Formulario)this.comboFormularioMaestro.getSelectedItem();
        //maestroDetalle.formularioDetalle=(Formulario)this.comboFormularioDetalle.getSelectedItem();

        simetria.formulario1 = new Formulario(((MiDato) this.comboForm1.getSelectedItem()).ID, ((MiDato) this.comboForm1.getSelectedItem()).nombre);
        //maestroDetalle.formularioDetalle

        simetria.formulario2 = new Formulario(((MiDato) this.comboForm2.getSelectedItem()).ID, ((MiDato) this.comboForm2.getSelectedItem()).nombre);
        simetria.vectorCamposForm1Seleccionados = this.modeloForm1Seleccionados;
        simetria.vectorCamposForm2Seleccionados = this.modeloForm2Seleccionados;
        simetria.setIDCampoLlaveForm1((TipoCampo) this.comboCampoLlaveForm1.getSelectedItem());
        simetria.setIDCampoLlaveForm2((TipoCampo) this.comboCampoLlaveForm2.getSelectedItem());
        simetria.agregarSimetria();
        this.dispose();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCargarCamposForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCamposForm2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.print("ID" + "  " + ((MiDato) comboForm1.getSelectedItem()).ID + "nombre" + "  " + ((MiDato) comboForm1.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        modeloForm2CamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm2.getSelectedItem()).ID);
        listaCampoForm2Disponibles.setListData(modeloForm2CamposDisponibles);

        /***********Se llena el combo de campos llave****************/
        javax.swing.DefaultComboBoxModel modeloCamposForm2 = new javax.swing.DefaultComboBoxModel();
        Vector vectorCampos = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm2.getSelectedItem()).ID);

        for (int i = 0; i < vectorCampos.size(); i++) {
            modeloCamposForm2.addElement(vectorCampos.get(i)/*.toString()*/);
        }
        comboCampoLlaveForm2.setModel(modeloCamposForm2);
    }//GEN-LAST:event_btnCargarCamposForm2ActionPerformed

    private void listaCampoForm2DisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCampoForm2DisponiblesMouseClicked
        // TODO add your handling code here:


        modeloForm2Seleccionados.add(listaCampoForm2Disponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposForm2Seleccionados.setListData(modeloForm2Seleccionados);
        int a = listaCampoForm2Disponibles.getSelectedIndex();
        System.out.print("aa: " + a);
        //modeloMaestroSeleccionados.remove(a);
        modeloForm2CamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCampoForm2Disponibles.setListData(modeloForm2CamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT
    }//GEN-LAST:event_listaCampoForm2DisponiblesMouseClicked

    private void comboCampoLlaveForm1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm1MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm1MouseReleased

    private void comboCampoLlaveForm1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm1ItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm1ItemStateChanged

    private void comboCampoLlaveForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm1ActionPerformed

    private void comboCampoLlaveForm2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm2MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm2MouseReleased

    private void comboCampoLlaveForm2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm2ItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm2ItemStateChanged

    private void comboCampoLlaveForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoLlaveForm2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboCampoLlaveForm2ActionPerformed

    /// <summary>
    /// main que crea un nuevo frameSimetria
    /// </summary>
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frameSimetria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarCamposForm1;
    private javax.swing.JButton btnCargarCamposForm2;
    private javax.swing.JComboBox comboCampoLlaveForm1;
    private javax.swing.JComboBox comboCampoLlaveForm2;
    private javax.swing.JComboBox comboForm1;
    private javax.swing.JComboBox comboForm2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listaCampoForm2Disponibles;
    private javax.swing.JList listaCamposForm1Disponibles;
    private javax.swing.JList listaCamposForm1Seleccionados;
    private javax.swing.JList listaCamposForm2Seleccionados;
    // End of variables declaration//GEN-END:variables
}
