/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameMaestroDetalle.java
 *
 * Created on 01/07/2009, 09:28:50 AM
 */

package gestiontipocampo;

/**
 *
 * @author ea61521
 */
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
public class frameMaestroDetalle extends javax.swing.JFrame {

    /** Creates new form frameMaestroDetalle */
    Vector modeloMaestroSeleccionados;
    Vector modeloMaestroCamposDisponibles;

    Vector modeloDetalleSeleccionados;
    Vector modeloDetalleCamposDisponibles;

    MaestroDetalle maestroDetalle;
    public Formulario formulario;

    public frameMaestroDetalle() {
        initComponents();
        formulario= new Formulario();
        llenarComboFormularios();
        maestroDetalle = new MaestroDetalle();
        modeloMaestroSeleccionados= new Vector();
        modeloDetalleSeleccionados= new Vector();

    }
    private void llenarComboFormularios() {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) comboFormularioMaestro.getModel();
        modelo.removeAllElements();
        modelo2.removeAllElements();
        formulario = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getTodosLosFormulario();
        int id;
        String nombreForm;
        for (int i = 0; i < forms.size(); i++) {
            id = Integer.parseInt(forms.get(i).toString());
            i++;
            nombreForm = forms.get(i).toString();
            modelo.addElement(new MiDato(nombreForm, id));
            modelo2.addElement(new MiDato(nombreForm, id));
        }
        comboFormularioMaestro.setModel(modelo);
        comboFormularioDetalle.setModel(modelo2);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboFormularioMaestro = new javax.swing.JComboBox();
        comboFormularioDetalle = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCamposMaestroDisponibles = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCampoDetalleDisponibles = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCamposMaestroSeleccionados = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCamposDetalleSeleccionados = new javax.swing.JList();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboCampoLlaveMaestro = new javax.swing.JComboBox();
        comboCampoLLaveDetalle = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        detalleObligatorio = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameMaestroDetalle.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        comboFormularioMaestro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFormularioMaestro.setName("comboFormularioMaestro"); // NOI18N
        comboFormularioMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboFormularioMaestroMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboFormularioMaestroMouseReleased(evt);
            }
        });
        comboFormularioMaestro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormularioMaestroItemStateChanged(evt);
            }
        });
        comboFormularioMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormularioMaestroActionPerformed(evt);
            }
        });

        comboFormularioDetalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFormularioDetalle.setName("comboFormularioDetalle"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaCamposMaestroDisponibles.setName("listaCamposMaestroDisponibles"); // NOI18N
        listaCamposMaestroDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCamposMaestroDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCamposMaestroDisponibles);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listaCampoDetalleDisponibles.setName("listaCampoDetalleDisponibles"); // NOI18N
        listaCampoDetalleDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCampoDetalleDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaCampoDetalleDisponibles);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        listaCamposMaestroSeleccionados.setName("listaCamposMaestroSeleccionados"); // NOI18N
        jScrollPane3.setViewportView(listaCamposMaestroSeleccionados);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        listaCamposDetalleSeleccionados.setName("listaCamposDetalleSeleccionados"); // NOI18N
        jScrollPane4.setViewportView(listaCamposDetalleSeleccionados);

        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("buttonDesplegarTiposCampoMaestro.text")); // NOI18N
        jButton3.setName("buttonDesplegarTiposCampoMaestro"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        comboCampoLlaveMaestro.setName("comboCampoLlaveMaestro"); // NOI18N
        comboCampoLlaveMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboCampoLlaveMaestroMouseReleased(evt);
            }
        });
        comboCampoLlaveMaestro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCampoLlaveMaestroItemStateChanged(evt);
            }
        });
        comboCampoLlaveMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoLlaveMaestroActionPerformed(evt);
            }
        });

        comboCampoLLaveDetalle.setName("comboCampoLlaveMaestro"); // NOI18N
        comboCampoLLaveDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboCampoLLaveDetalleMouseReleased(evt);
            }
        });
        comboCampoLLaveDetalle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCampoLLaveDetalleItemStateChanged(evt);
            }
        });
        comboCampoLLaveDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoLLaveDetalleActionPerformed(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        detalleObligatorio.setText(resourceMap.getString("detalleObligatorio.text")); // NOI18N
        detalleObligatorio.setName("detalleObligatorio"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboFormularioMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(comboCampoLlaveMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboFormularioDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboCampoLLaveDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(detalleObligatorio)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFormularioMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFormularioDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCampoLlaveMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCampoLLaveDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalleObligatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFormularioMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormularioMaestroActionPerformed


        /*    System.out.print("ID" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloMaestroCamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);


        comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCamposMaestroDisponibles.setListData(modeloMaestroCamposDisponibles);
        
      /*
System.out.print("asdfasdf" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getMiembrosFormularioPorID(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);
        int id;
        String tipoCampo;
        int tipoDeTipoCampo;
        for (int i = 0; i < forms.size(); i++) {
            id = Integer.parseInt(forms.get(i).toString());
            i++;
            tipoCampo = forms.get(i).toString();
            i++;
            tipoDeTipoCampo = Integer.parseInt(forms.get(i).toString());
            modelo.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
            modelo2.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
        }

        //comboCampoInicial.setModel(modelo);
       // comboCampoFinal.setModel(modelo2);

        comboFormularioDetalle.setModel(modelo);*/

}//GEN-LAST:event_comboFormularioMaestroActionPerformed

    private void comboFormularioMaestroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormularioMaestroItemStateChanged
      
    }//GEN-LAST:event_comboFormularioMaestroItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.out.print("ID" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();

        modeloMaestroCamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);

        listaCamposMaestroDisponibles.setListData(modeloMaestroCamposDisponibles);

        javax.swing.DefaultComboBoxModel modeloCamposDetalle = new javax.swing.DefaultComboBoxModel();

        Vector vectorCampos = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);

        for (int i = 0; i < vectorCampos.size(); i++) {
            modeloCamposDetalle.addElement(vectorCampos.get(i).toString());
        }
        comboCampoLlaveMaestro.setModel(modeloCamposDetalle);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboFormularioMaestroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFormularioMaestroMouseReleased

    }//GEN-LAST:event_comboFormularioMaestroMouseReleased

    private void listaCamposMaestroDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCamposMaestroDisponiblesMouseClicked
        // TODO add your handling code here:


        modeloMaestroSeleccionados.add(listaCamposMaestroDisponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposMaestroSeleccionados.setListData(modeloMaestroSeleccionados);
        int a=listaCamposMaestroDisponibles.getSelectedIndex();
        System.out.print("aa: "+a);
        //modeloMaestroSeleccionados.remove(a);
        modeloMaestroCamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCamposMaestroDisponibles.setListData(modeloMaestroCamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT

    }//GEN-LAST:event_listaCamposMaestroDisponiblesMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
        //maestroDetalle.formularioMaestro=(Formulario)this.comboFormularioMaestro.getSelectedItem();
        //maestroDetalle.formularioDetalle=(Formulario)this.comboFormularioDetalle.getSelectedItem();

        maestroDetalle.formularioMaestro= new Formulario(((MiDato)this.comboFormularioMaestro.getSelectedItem()).ID,((MiDato)this.comboFormularioMaestro.getSelectedItem()).nombre);
        //maestroDetalle.formularioDetalle

        maestroDetalle.formularioDetalle=new Formulario(((MiDato)this.comboFormularioDetalle.getSelectedItem()).ID,((MiDato)this.comboFormularioDetalle.getSelectedItem()).nombre);
        maestroDetalle.vectorCamposDetalleSeleccionados = this.modeloDetalleSeleccionados;
        maestroDetalle.vectorCamposMaestroSeleccionados = this.modeloMaestroSeleccionados;

        maestroDetalle.detalleObligatorio = this.detalleObligatorio.isSelected()?"TRUE":"FALSE";

        maestroDetalle.agregarNuevoMaestroDetalle();
        this.dispose();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // TODO add your handling code here:
                // TODO add your handling code here:
        System.out.print("ID" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).nombre);        // TODO add your handling code here:

       /* javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();*/

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloDetalleCamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioDetalle.getSelectedItem()).ID);


        //comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCampoDetalleDisponibles.setListData(modeloDetalleCamposDisponibles);


        javax.swing.DefaultComboBoxModel modeloCamposDetalle = new javax.swing.DefaultComboBoxModel();
        Vector vectorCampos = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);
        for (int i = 0; i < vectorCampos.size(); i++) {
            modeloCamposDetalle.addElement(vectorCampos.get(i).toString());
        }
        comboCampoLLaveDetalle.setModel(modeloCamposDetalle);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void listaCampoDetalleDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCampoDetalleDisponiblesMouseClicked
        // TODO add your handling code here:


        modeloDetalleSeleccionados.add(listaCampoDetalleDisponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposDetalleSeleccionados.setListData(modeloDetalleSeleccionados);
        int a=listaCampoDetalleDisponibles.getSelectedIndex();
        System.out.print("aa: "+a);
        //modeloMaestroSeleccionados.remove(a);
        modeloDetalleCamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCampoDetalleDisponibles.setListData(modeloDetalleCamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT
    }//GEN-LAST:event_listaCampoDetalleDisponiblesMouseClicked

    private void comboCampoLlaveMaestroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCampoLlaveMaestroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLlaveMaestroMouseReleased

    private void comboCampoLlaveMaestroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCampoLlaveMaestroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLlaveMaestroItemStateChanged

    private void comboCampoLlaveMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoLlaveMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLlaveMaestroActionPerformed

    private void comboCampoLLaveDetalleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCampoLLaveDetalleMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLLaveDetalleMouseReleased

    private void comboCampoLLaveDetalleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCampoLLaveDetalleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLLaveDetalleItemStateChanged

    private void comboCampoLLaveDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoLLaveDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoLLaveDetalleActionPerformed

    private void comboFormularioMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboFormularioMaestroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFormularioMaestroMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMaestroDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox comboCampoLLaveDetalle;
    private javax.swing.JComboBox comboCampoLlaveMaestro;
    private javax.swing.JComboBox comboFormularioDetalle;
    private javax.swing.JComboBox comboFormularioMaestro;
    private javax.swing.JCheckBox detalleObligatorio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listaCampoDetalleDisponibles;
    private javax.swing.JList listaCamposDetalleSeleccionados;
    private javax.swing.JList listaCamposMaestroDisponibles;
    private javax.swing.JList listaCamposMaestroSeleccionados;
    // End of variables declaration//GEN-END:variables

}
