/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameMaestroDetalle.java
 *
 * Created on 01/07/2009, 09:28:50 AM
 */

package gestiontipocampo;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
public class frameSimetria extends javax.swing.JFrame {

    /** Creates new form frameMaestroDetalle */
    Vector modeloForm1Seleccionados;
    Vector modeloForm1CamposDisponibles;

    Vector modeloForm2Seleccionados;
    Vector modeloForm2CamposDisponibles;

    Simetria simetria;
    public Formulario formulario;

    public frameSimetria() {
        initComponents();
        formulario= new Formulario();
        llenarComboFormularios();
        simetria = new Simetria();
        modeloForm1Seleccionados= new Vector();
        modeloForm2Seleccionados= new Vector();

    }
    private void llenarComboFormularios() {
        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo = (DefaultComboBoxModel) comboForm1.getModel();
        modelo.removeAllElements();
        modelo2.removeAllElements();
        formulario = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getTodosLosFormulario();
        int id;
        String nombreForm;
        for (int i = 0; i < forms.size(); i++) {
            id = Integer.parseInt(forms.get(i).toString());
            i++;
            nombreForm = forms.get(i).toString();
            modelo.addElement(new MiDato(nombreForm, id));
            modelo2.addElement(new MiDato(nombreForm, id));
        }
        comboForm1.setModel(modelo);
        comboForm2.setModel(modelo2);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboForm1 = new javax.swing.JComboBox();
        comboForm2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCamposForm1Disponibles = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCampoForm2Disponibles = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCamposForm1Seleccionados = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCamposForm2Seleccionados = new javax.swing.JList();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        comboForm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboForm1.setName("comboForm1"); // NOI18N
        comboForm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboForm1MouseReleased(evt);
            }
        });
        comboForm1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboForm1ItemStateChanged(evt);
            }
        });
        comboForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboForm1ActionPerformed(evt);
            }
        });

        comboForm2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboForm2.setName("comboForm2"); // NOI18N

        jLabel2.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaCamposForm1Disponibles.setName("listaCamposForm1Disponibles"); // NOI18N
        listaCamposForm1Disponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCamposForm1DisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCamposForm1Disponibles);

        jLabel3.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listaCampoForm2Disponibles.setName("listaCampoForm2Disponibles"); // NOI18N
        listaCampoForm2Disponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCampoForm2DisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaCampoForm2Disponibles);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        listaCamposForm1Seleccionados.setName("listaCamposForm1Seleccionados"); // NOI18N
        jScrollPane3.setViewportView(listaCamposForm1Seleccionados);

        jLabel4.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        listaCamposForm2Seleccionados.setName("listaCamposForm2Seleccionados"); // NOI18N
        jScrollPane4.setViewportView(listaCamposForm2Seleccionados);

        btnAceptar.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        jButton3.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("buttonDesplegarTiposCampoMaestro.text")); // NOI18N
        jButton3.setName("buttonDesplegarTiposCampoMaestro"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText(org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameSimetria.class).getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jButton3))
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButton4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboForm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboForm1ActionPerformed
         /*    System.out.print("ID" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloMaestroCamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);


        comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCamposMaestroDisponibles.setListData(modeloMaestroCamposDisponibles);
        
      /*
System.out.print("asdfasdf" + "  " + ((MiDato) comboFormularioMaestro.getSelectedItem()).ID);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();
        Vector forms = new Vector();
        forms = formulario.getMiembrosFormularioPorID(((MiDato) comboFormularioMaestro.getSelectedItem()).ID);
        int id;
        String tipoCampo;
        int tipoDeTipoCampo;
        for (int i = 0; i < forms.size(); i++) {
            id = Integer.parseInt(forms.get(i).toString());
            i++;
            tipoCampo = forms.get(i).toString();
            i++;
            tipoDeTipoCampo = Integer.parseInt(forms.get(i).toString());
            modelo.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
            modelo2.addElement(new TipoCampo(tipoDeTipoCampo, tipoCampo, id));
        }

        //comboCampoInicial.setModel(modelo);
       // comboCampoFinal.setModel(modelo2);

        comboFormularioDetalle.setModel(modelo);*/

}//GEN-LAST:event_comboForm1ActionPerformed

    private void comboForm1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboForm1ItemStateChanged
      
    }//GEN-LAST:event_comboForm1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  // TODO add your handling code here:
               // TODO add your handling code here:
        System.out.println("ID" + "  " + ((MiDato) comboForm1.getSelectedItem()).ID+" nombre" + "  " + ((MiDato) comboForm1.getSelectedItem()).nombre);        // TODO add your handling code here:

        javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloForm1CamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm1.getSelectedItem()).ID);


        //comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCamposForm1Disponibles.setListData(modeloForm1CamposDisponibles);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboForm1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboForm1MouseReleased

    }//GEN-LAST:event_comboForm1MouseReleased

    private void listaCamposForm1DisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCamposForm1DisponiblesMouseClicked
        // TODO add your handling code here:


        modeloForm1Seleccionados.add(listaCamposForm1Disponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposForm1Seleccionados.setListData(modeloForm1Seleccionados);
        int a=listaCamposForm1Disponibles.getSelectedIndex();
        System.out.print("aa: "+a);
        //modeloMaestroSeleccionados.remove(a);
        modeloForm1CamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCamposForm1Disponibles.setListData(modeloForm1CamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT

    }//GEN-LAST:event_listaCamposForm1DisponiblesMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
        //maestroDetalle.formularioMaestro=(Formulario)this.comboFormularioMaestro.getSelectedItem();
        //maestroDetalle.formularioDetalle=(Formulario)this.comboFormularioDetalle.getSelectedItem();

        simetria.formulario1= new Formulario(((MiDato)this.comboForm1.getSelectedItem()).ID,((MiDato)this.comboForm1.getSelectedItem()).nombre);
        //maestroDetalle.formularioDetalle

        simetria.formulario2= new Formulario(((MiDato)this.comboForm2.getSelectedItem()).ID,((MiDato)this.comboForm2.getSelectedItem()).nombre);
        simetria.vectorCamposForm1Seleccionados = this.modeloForm1Seleccionados;
        simetria.vectorCamposForm2Seleccionados = this.modeloForm2Seleccionados;
        simetria.agregarSimetria();
        this.dispose();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        System.out.print("ID" + "  " + ((MiDato) comboForm1.getSelectedItem()).ID+"nombre" + "  " + ((MiDato) comboForm1.getSelectedItem()).nombre);        // TODO add your handling code here:

       /* javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
        modelo.removeAllElements();*/

        javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
        modelo2.removeAllElements();
        //comandoActual = new Comando(); // Clase comando con la que trabajara la interfaz

        //formularioActual = new Formulario();

        modeloForm2CamposDisponibles = formulario.getMiembrosFormularioPorIDSoloNombre(((MiDato) comboForm2.getSelectedItem()).ID);


        //comboFormularioDetalle.setModel(modelo);        // TODO add your handling code here:
        listaCampoForm2Disponibles.setListData(modeloForm2CamposDisponibles);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void listaCampoForm2DisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCampoForm2DisponiblesMouseClicked
        // TODO add your handling code here:


        modeloForm2Seleccionados.add(listaCampoForm2Disponibles.getSelectedValue()/*.toString()*/);

        //listaCamposMaestroDisponibles.remove(0);
        listaCamposForm2Seleccionados.setListData(modeloForm2Seleccionados);
        int a=listaCampoForm2Disponibles.getSelectedIndex();
        System.out.print("aa: "+a);
        //modeloMaestroSeleccionados.remove(a);
        modeloForm2CamposDisponibles.remove(a);
        //listaCamposMaestroDisponibles.remo
        listaCampoForm2Disponibles.setListData(modeloForm2CamposDisponibles);
        //listaCamposMaestroDisponibles.ABORT
    }//GEN-LAST:event_listaCampoForm2DisponiblesMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameSimetria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboForm1;
    private javax.swing.JComboBox comboForm2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listaCampoForm2Disponibles;
    private javax.swing.JList listaCamposForm1Disponibles;
    private javax.swing.JList listaCamposForm1Seleccionados;
    private javax.swing.JList listaCamposForm2Seleccionados;
    // End of variables declaration//GEN-END:variables

}
