/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameAbriMaestroDetalle.java
 *
 * Created on 09/07/2009, 03:06:48 AM
 */

package gestiontipocampo;

/**
 *
 * @author Administrator
 */
import java.util.*;
public class frameAbriMaestroDetalle extends javax.swing.JFrame {

    /** Creates new form frameAbriMaestroDetalle */
    public MaestroDetalle maestroDetalle;

    public frameAbriMaestroDetalle() {
        initComponents();
        maestroDetalle = new MaestroDetalle();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMaestroDetalles = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameAbriMaestroDetalle.class);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setRequestFocusEnabled(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaMaestroDetalles.setName("listaMaestroDetalles"); // NOI18N
        listaMaestroDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMaestroDetallesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaMaestroDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaMaestroDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMaestroDetallesMouseClicked
        // TODO add your handling code here:



}//GEN-LAST:event_listaMaestroDetallesMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Vector vectorFuente=this.maestroDetalle.obtenerTodosLosMaestroDetalle();
        Vector vectorNuevo= new Vector();

        for(int i=0; i<vectorFuente.size(); i++){
            vectorNuevo.add(new MaestroDetalle(vectorFuente.get(i).toString(),vectorFuente.get(i+1).toString()));
            i++;
        }
                this.listaMaestroDetalles.setListData(vectorNuevo);
    }//GEN-LAST:event_formComponentShown

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAbriMaestroDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaMaestroDetalles;
    // End of variables declaration//GEN-END:variables

}
