/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameActividad.java
 *
 * Created on 16/06/2009, 08:39:38 AM
 */

package gestiontipocampo;

/**
 *
 * @author Alberto
 */
public class frameActividad extends javax.swing.JFrame {

    /** Creates new form frameActividad */
    public frameActividad() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        labelDescripcion = new javax.swing.JLabel();
        fieldDescripcion = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        labelSeleccionFormulario = new javax.swing.JLabel();
        comboSeleccionFormulario = new javax.swing.JComboBox();
        labelCampoInicial = new javax.swing.JLabel();
        comboComandoAAgregar = new javax.swing.JComboBox();
        botonAgregarComando = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        labelCampoInicial1 = new javax.swing.JLabel();
        comboComandoAAgregar1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        panelChecksParalelo = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameActividad.class);
        labelNombre.setText(resourceMap.getString("labelNombre.text")); // NOI18N
        labelNombre.setName("labelNombre"); // NOI18N

        fieldNombre.setName("fieldNombre"); // NOI18N

        labelTipo.setText(resourceMap.getString("labelTipo.text")); // NOI18N
        labelTipo.setName("labelTipo"); // NOI18N

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Compuesto"} ));
        comboTipo.setName("comboTipo"); // NOI18N
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        labelDescripcion.setText(resourceMap.getString("labelDescripcion.text")); // NOI18N
        labelDescripcion.setName("labelDescripcion"); // NOI18N

        fieldDescripcion.setName("fieldDescripcion"); // NOI18N

        botonCancelar.setText(resourceMap.getString("botonCancelar.text")); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText(resourceMap.getString("botonAceptar.text")); // NOI18N
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelSeleccionFormulario.setText(resourceMap.getString("labelSeleccionFormulario.text")); // NOI18N
        labelSeleccionFormulario.setName("labelSeleccionFormulario"); // NOI18N

        comboSeleccionFormulario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        comboSeleccionFormulario.setName("comboSeleccionFormulario"); // NOI18N
        comboSeleccionFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionFormularioActionPerformed(evt);
            }
        });

        labelCampoInicial.setText(resourceMap.getString("labelCampoInicial.text")); // NOI18N
        labelCampoInicial.setName("labelCampoInicial"); // NOI18N
        labelCampoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCampoInicialMouseClicked(evt);
            }
        });

        comboComandoAAgregar.setName("comboComandoAAgregar"); // NOI18N
        comboComandoAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComandoAAgregarActionPerformed(evt);
            }
        });

        botonAgregarComando.setText(resourceMap.getString("botonAgregarComando.text")); // NOI18N
        botonAgregarComando.setName("botonAgregarComando"); // NOI18N
        botonAgregarComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarComandoActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        labelCampoInicial1.setText(resourceMap.getString("labelCampoInicial1.text")); // NOI18N
        labelCampoInicial1.setName("labelCampoInicial1"); // NOI18N
        labelCampoInicial1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCampoInicial1MouseClicked(evt);
            }
        });

        comboComandoAAgregar1.setName("comboComandoAAgregar1"); // NOI18N
        comboComandoAAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComandoAAgregar1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox3.setText(resourceMap.getString("jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        panelChecksParalelo.setName("panelChecksParalelo"); // NOI18N

        jCheckBox2.setText(resourceMap.getString("jCheckBox2.text")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        jCheckBox4.setText(resourceMap.getString("jCheckBox4.text")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        javax.swing.GroupLayout panelChecksParaleloLayout = new javax.swing.GroupLayout(panelChecksParalelo);
        panelChecksParalelo.setLayout(panelChecksParaleloLayout);
        panelChecksParaleloLayout.setHorizontalGroup(
            panelChecksParaleloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChecksParaleloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChecksParaleloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelChecksParaleloLayout.setVerticalGroup(
            panelChecksParaleloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChecksParaleloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jCheckBox4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre)
                                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTipo)))
                            .addComponent(labelSeleccionFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescripcion)))
                    .addComponent(comboSeleccionFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelCampoInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboComandoAAgregar1, 0, 130, Short.MAX_VALUE)
                                    .addComponent(labelCampoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboComandoAAgregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonAgregarComando))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3))
                                .addGap(38, 38, 38)
                                .addComponent(panelChecksParalelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(labelSeleccionFormulario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipo)
                            .addComponent(labelDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSeleccionFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(labelCampoInicial1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboComandoAAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1))
                                .addGap(18, 18, 18)
                                .addComponent(labelCampoInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboComandoAAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox3))
                                .addGap(36, 36, 36)
                                .addComponent(botonAgregarComando))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(panelChecksParalelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAceptar)
                            .addComponent(botonCancelar))
                        .addGap(73, 73, 73))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed

}//GEN-LAST:event_comboTipoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
}//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        //String nombreFormulario = ((MiDato)this.comboSeleccionFormulario.getSelectedItem()).nombre;
        //Se inicializan los campos del Comando
        int IDComandoAgregado=0;
        /*
        comandoActual.IDFormulario=((MiDato)this.comboSeleccionFormulario.getSelectedItem()).ID;
        comandoActual.IDFormularioTrabajar=comandoActual.IDFormulario;//este no sé para que es, en el script del profe no se usa
        comandoActual.descripcion=this.fieldDescripcion.getText();
        comandoActual.nombreComando=this.fieldNombre.getText();
        comandoActual.setTipoComando(this.comboTipo.getSelectedIndex() + 1);

        IDComandoAgregado=comandoActual.guardarComandoSinMascara();

        if(ConMascara==1){
            comandoActual.condicionInicial=fieldAccion.getText();
            comandoActual.estadoFinal=fieldEfecto.getText();
            comandoActual.tipoCampoInicial=((MiDato)comboComandoNuevo.getSelectedItem()).nombre;
            comandoActual.tipoCampoFinal=((MiDato)comboCampoFinal.getSelectedItem()).nombre;
            comandoActual.IDComando=IDComandoAgregado;///Esto es lo unico que hace falta arreglar esto
        }

        comandoActual.guardarComandoConMascara();
        //comandoActual.conMascara=true;
        // comandoActual.guardarComando();
*/
        this.dispose();
}//GEN-LAST:event_botonAceptarActionPerformed

    private void comboSeleccionFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionFormularioActionPerformed
        
    }//GEN-LAST:event_comboSeleccionFormularioActionPerformed

    private void labelCampoInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCampoInicialMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_labelCampoInicialMouseClicked

    private void comboComandoAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComandoAAgregarActionPerformed

        /*
        System.out.print(((TipoCampo)comboComandoAAgregar.getSelectedItem()).tipoDeTipoCampo);
        int tipoDeTipoCampo=((TipoCampo)comboComandoAAgregar.getSelectedItem()).tipoDeTipoCampo;
        //int correlativoTipoCampo=((TipoCampo)comboCampoInicial.getSelectedItem()).correlativo;
        int correlativoTipoCampo=555; //ya casi arregle esto, luisk
        Lista lista;
        if(frameManejoCampos.LISTA==tipoDeTipoCampo){
            lista=new Lista();


            javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
            //----------------------------------
            Vector miembrosLista;
            miembrosLista=lista.getMiembrosListaPorIDLista(correlativoTipoCampo);
            int id;
            String miembroLista;
            for(int i=0;i<miembrosLista.size(); i++){
                //id=Integer.parseInt(miembrosLista.get(i).toString());
                // i++;
                miembroLista=miembrosLista.get(i).toString();


                modelo.addElement(new MiDato(miembroLista, 0));

            }


            //-----------------------------------
            comboListaCondicion.setModel(modelo);
            comboListaCondicion.setVisible(true);
        } else{
            comboListaCondicion.setVisible(false);
        }
          */
}//GEN-LAST:event_comboComandoAAgregarActionPerformed

    private void botonAgregarComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarComandoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botonAgregarComandoActionPerformed

    private void labelCampoInicial1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCampoInicial1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCampoInicial1MouseClicked

    private void comboComandoAAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComandoAAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboComandoAAgregar1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAgregarComando;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboComandoAAgregar;
    private javax.swing.JComboBox comboComandoAAgregar1;
    private javax.swing.JComboBox comboSeleccionFormulario;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCampoInicial;
    private javax.swing.JLabel labelCampoInicial1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSeleccionFormulario;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelChecksParalelo;
    // End of variables declaration//GEN-END:variables

}
